name: build and test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create build directory
          run: mkdir build
          
        - name: Configure CMake
          working-directory: ${{github.workspace}}/build
          run: cmake ..
        
        - name: Build project
          working-directory: ${{github.workspace}}/build
          run: cmake --build .
          
        - name: Run CTest
          working-directory: ${{github.workspace}}/build
          run: ctest --output-on-failure