name: build and test

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create build directory
          run: mkdir build
          
        - name: Configure CMake
          working-directory: ${{github.workspace}}/build
          run: cmake ..
        
        - name: Build project
          working-directory: ${{github.workspace}}/build
          run: cmake --build .

        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-artifacts
            path: ${{github.workspace}}/build
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Download Build Artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-artifacts
            path: ${{github.workspace}}/build

        - name: Run CTest
          working-directory: ${{github.workspace}}/build
          run: sudo ctest --output-on-failure